1. Instalēt TensorFlow objektu noteikšanas pakotnes

In [ ]:
!sudo apt install unzip
!unzip /home/midtempo/SSD/trained_model/custom_model_lite.zip

In [1]:
# Clone the tensorflow models repository from GitHub
!pip uninstall Cython -y # Temporary fix for "No module named 'object_detection'" error
!git clone -b r2.12.0 https://github.com/tensorflow/models.git
!cd models && git checkout 115409fcafdf5098855c8ca18c4f87c14174ffe1

Cloning into 'models'...
remote: Enumerating objects: 97260, done.
remote: Counting objects: 100% (540/540), done.
remote: Compressing objects: 100% (264/264), done.
remote: Total 97260 (delta 320), reused 455 (delta 272), pack-reused 96720
Receiving objects: 100% (97260/97260), 612.91 MiB | 8.30 MiB/s, done.
Resolving deltas: 100% (70738/70738), done.
Note: switching to '115409fcafdf5098855c8ca18c4f87c14174ffe1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 115409fca Internal change


In [ ]:
pip install tensorflow
pip install opencv-python
pip uninstall protobuf
# pip install protobuf==3.20.0
# conda install protobuf=3.20

In [13]:
import importlib.util
pkg = importlib.util.find_spec('tflite_runtime')
print(pkg)

None


In [ ]:
# Update package lists and install wget
sudo apt update
sudo apt install wget unzip

# Download and unzip protoc 3.20.1
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-linux-x86_64.zip
unzip protoc-3.20.1-linux-x86_64.zip -d protoc-3.20.1

# Move the binaries to /usr/local/bin and includes to /usr/local/include
sudo mv protoc-3.20.1/bin/protoc /usr/local/bin/
sudo mv protoc-3.20.1/include/* /usr/local/include/

# Verify the installation
protoc --version


In [1]:
%%bash
cd models/research/
protoc object_detection/protos/*.proto --python_out=.

In [3]:
import re
import os

# Get the current working directory
cwd = os.getcwd()

input_path = os.path.join(cwd, 'models/research/object_detection/packages/tf2/setup.py')
output_path = os.path.join(cwd, 'models/research/setup.py')

# Read the content of the input setup.py file
with open(input_path, 'r') as f:
    content = f.read()

# Modify the tf-models-official version requirement
modified_content = re.sub(r'tf-models-official>=2.5.1', r'tf-models-official==2.8.0', content)

# Write the modified content to the output setup.py file
with open(output_path, 'w') as f:
    f.write(modified_content)

In [3]:
# Need to do a temporary fix with PyYAML because Colab isn't able to install PyYAML v5.4.1
!pip install pyyaml==5.3
!pip install /home/midtempo/SSD/models/research/

# Need to downgrade to TF v2.8.0 due to Colab compatibility bug with TF v2.10 (as of 10/03/22)
!pip install tensorflow==2.8.0

# Install CUDA version 11.0 (to maintain compatibility with TF v2.8.0)
!pip install tensorflow_io==0.23.1
# !wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
# !mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
# !wget http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda-repo-ubuntu1804-11-0-local_11.0.2-450.51.05-1_amd64.deb
# !dpkg -i cuda-repo-ubuntu1804-11-0-local_11.0.2-450.51.05-1_amd64.deb
# !apt-key add /var/cuda-repo-ubuntu1804-11-0-local/7fa2af80.pub
# !apt-get update && sudo apt-get install cuda-toolkit-11-0
# !export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:$LD_LIBRARY_PATH

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.2/268.2 kB 457.9 kB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3-cp39-cp39-linux_x86_64.whl size=44244 sha256=b41736825708d58105101f88e99d4f3455fec0b36a61a24943518e904755b80b
  Stored in directory: /home/midtempo/.cache/pip/wheels/b8/91/58/7cbe3f1dd6ba39ab89041441e6e01fc8361fbddac40aaea52d
Successfully built pyyaml
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.1
    Uninstalling PyYAML-6.0.1:
      Successfully uninstalled PyYAML-6.0.1
ERROR: Invalid requirement: '/content/models/research/'
Hint: It looks like a path. File '/content/models/research/' does not exist.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 497.6/497.6 MB 4.5 MB/s eta 0:00:0000:0100:02m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.5/462.5 kB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [4]:
# Run Model Bulider Test file, just to verify everything's working properly
!python ./models/research/object_detection/builders/model_builder_tf2_test.py


2024-06-04 23:58:22.209519: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-06-04 23:58:22.209571: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-06-04 23:58:28.376451: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-04 23:58:28.376629: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-06-04 23:58:28.376725: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcub

#  Run TensorFlow Lite Model!

In [ ]:
curl https://raw.githubusercontent.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/master/TFLite_detection_image.py --output TFLite_detection_image.py

In [8]:
!python TFLite_detection_image.py --modeldir=ssd_model_lite --imagedir images --save_results --noshow_results

2024-06-04 23:59:30.859398: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/midtempo/miniconda3/envs/tf-ssd/lib/python3.9/site-packages/cv2/../../lib64:
2024-06-04 23:59:30.859443: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


In [4]:
import tensorflow as tf

# Check if TensorFlow is built with CUDA (which includes cuDNN)
cuda_built = tf.test.is_built_with_cuda()
print(f"TensorFlow built with CUDA: {cuda_built}")

# List all physical devices visible to TensorFlow
physical_devices = tf.config.list_physical_devices('GPU')
if physical_devices:
    print(f"Number of GPUs available: {len(physical_devices)}")
    for device in physical_devices:
        print(f"Device: {device}")
else:
    print("No GPU devices available")

# Verify cuDNN availability by attempting to perform a simple operation
try:
    with tf.device('/GPU:0'):
        a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        b = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        c = tf.matmul(a, b, transpose_a=True)
        print(f"Matrix multiplication result:\n{c}")
        print("cuDNN is available and working correctly.")
except RuntimeError as e:
    print(f"Error during GPU operation: {e}")
    print("cuDNN might not be available or correctly configured.")


2024-06-02 23:55:55.575425: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-06-02 23:55:55.575491: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


TensorFlow built with CUDA: True
No GPU devices available
Matrix multiplication result:
[[17. 22. 27.]
 [22. 29. 36.]
 [27. 36. 45.]]
cuDNN is available and working correctly.


2024-06-02 23:55:58.825909: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-02 23:55:58.826099: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-06-02 23:55:58.826186: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2024-06-02 23:55:58.826246: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2024-06-02 23:55:58.826302: W tensorflow/stream_executor/platform/default/dso_loader.cc:6

In [1]:
import torch
print(torch.cuda.is_available()) # should be True

t = torch.rand(10, 10).cuda()
print(t.device) # should be CUDA

True
cuda:0
